Repository antvis/F2, pull requests merged in 2019-12, with the labels that each got.

#725 fix: 修复Shape.Text 在设置 rotate 之后 Box 宽高不正确的问题
  src/graphic/shape/text.js
  src/graphic/util/rect.js
  test/unit/graphic/shape/text-spec.js
Labels: PR: unreviewed, bug

#727 fix: 修复数据经过分组之后，没有任何数据的分组也参与绘图计算，尤其是在柱状图中，会占用宽度.
  src/geom/base.js
  test/unit/geom/geom-spec.js
Labels: PR: unreviewed, bug

#729 fix: 滑动x轴时，cat的ticks会被置成null
  src/interaction/mixin/move.js
  test/unit/interaction/pan-spec.js
Labels: PR: unreviewed, bug

#730 chore: release 3.4.4
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#732 docs: 添加filter的使用说明
  docs/api/chart/chart.en.md
  docs/api/chart/chart.zh.md
Labels: PR: unreviewed, documentation

#737 chore(deps): upgrade eslint 3.19.0 to 6.7.2
  examples/component/legend/demo/custom.js
  package.json
  src/plugin/pie-label.js
  src/util/dom.js
  test/bug/issue-467-spec.js
  test/unit/chart/chart-spec.js
  test/unit/geom/geom-spec.js
Labels: PR: unreviewed, dependencies

#739 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
Labels: PR: unreviewed, documentation

#745 feat: 添加漏斗图
  demos/interval-symmetric.html
  src/coord/base.js
  src/coord/cartesian.js
  src/coord/polar.js
  src/geom/adjust/index.js
  src/geom/adjust/symmetric.js
  src/geom/base.js
  src/geom/shape/interval.js
  src/index-all.js
  src/plugin/interval-label.js
  test/unit/coord/base-spec.js
  test/unit/geom/geom-spec.js
  test/unit/plugin/interval-label-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#746 release 3.5-beta.2
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested

#747 feat: 添加漏斗图演示demo
  examples/funnel/basic/demo/basic.js
  examples/funnel/basic/demo/meta.json
  examples/funnel/basic/demo/stroke.js
  examples/funnel/basic/index.en.md
  examples/funnel/basic/index.zh.md
  examples/funnel/pyramid/demo/basic.js
  examples/funnel/pyramid/demo/meta.json
  examples/funnel/pyramid/demo/scale.js
  examples/funnel/pyramid/demo/stroke.js
  examples/funnel/pyramid/index.en.md
  examples/funnel/pyramid/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, enhancement

#748 refactor: 去掉eventemitter，只要简单的事件处理就可以了
  package.json
  src/global.js
  src/graphic/canvas-element.js
Labels: PR: reviewed-changes-requested, refactor
