Repository antvis/F2, pull requests merged in 2019-11, with the labels that each got.

#693 fix: f2 example throw require is not defined
  examples/basic/demo/basic.js
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, bug

#695 fix: 修复对类型换图点击选中的问题 #682
  src/geom/base.js
  test/bug/issue-67-spec.js
Labels: PR: reviewed-changes-requested, bug

#701 chore: Improve gatsby config
  gatsby-browser.js
  gatsby-config.js
  package.json
  site/global.less
Labels: PR: reviewed-changes-requested, chore

#703 fix: 修复只有1个点时，tooltip不显示的问题 #702
  src/geom/base.js
  test/bug/issue-702-spec.js
Labels: PR: reviewed-changes-requested, bug

#705 chore: release 3.4.3
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#706 chore: update .npmignore
  .npmignore
Labels: PR: unreviewed, chore

#708 🚀 f2.antv.vision
  README.md
  README.zh-CN.md
  gatsby-config.js
  package.json
Labels: PR: unreviewed

#710 Feat new site
  docs/api/chart/coordinate.en.md
  docs/api/chart/coordinate.zh.md
  docs/api/chart/interaction.en.md
  docs/api/chart/interaction.zh.md
  docs/api/chart/pie-label.en.md
  docs/api/chart/pie-label.zh.md
  docs/api/chart/scale.en.md
  docs/api/chart/scale.zh.md
  docs/api/chart/tooltip.en.md
  docs/api/chart/tooltip.zh.md
  docs/api/graphic/g.en.md
  docs/api/graphic/g.zh.md
  docs/api/graphic/group.en.md
  docs/api/graphic/group.zh.md
  docs/api/graphic/shape.en.md
  docs/api/graphic/shape.zh.md
  docs/api/shape.en.md
  docs/api/shape.zh.md
  docs/tutorial/getting-started.en.md
  docs/tutorial/getting-started.zh.md
  docs/tutorial/manual/scale.en.md
  docs/tutorial/manual/scale.zh.md
  docs/tutorial/question.en.md
  docs/tutorial/question.zh.md
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#714 Chore site
  examples/candlestick/basic/demo/daily.js
  examples/candlestick/basic/demo/hour.js
  examples/candlestick/basic/demo/meta.json
  examples/data/1d-k.json
  examples/data/hour-k.json
  examples/gallery/forecast/demo/meta.json
  examples/gallery/steps-record/demo/meta.json
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested
