Repository antvis/F2, pull requests merged in 2020-05, with the labels that each got.

#869 feat: 添加clear相关事件
  src/chart/chart.js
  src/chart/const.js
  src/graphic/event/controller.js
  test/unit/graphic/event/controller-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#870 chore: release 3.6.4-beta.3
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#875 feat: 添加geom draw 事件
  src/chart/chart.js
  src/chart/const.js
  src/chart/controller/scale.js
Labels: PR: reviewed-changes-requested, enhancement

#876 chore: release 3.6.4-beta.4
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#887 chore: release 3.7.0-alpha.0
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#888 fix: 修复site编译报错的问题
  .babelrc
  package.json
  src/coord/cartesian.js
  src/geom/area.js
  src/geom/shape/index.js
  src/geom/shape/line.js
  src/interaction/helper.js
Labels: PR: reviewed-changes-requested, bug

#889 feat: 添加esm的模块输出
  .babelrc
  .eslintignore
  .gitignore
  package.json
  rollup.config.js
Labels: PR: reviewed-changes-requested, enhancement

#890 chore: release 3.7.0-alpha.1
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#893 fix: 修复rect radius大于宽高时，图形绘制不正确
  src/graphic/shape/rect.js
  test/unit/graphic/shape/rect-spec.js
Labels: PR: unreviewed, bug

#894 chore: release 3.6.4-beta.5
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#897 fix: module mix fixed
  package.json
  src/interaction/mixin/move.js
  src/interaction/mixin/update-scale.js
  src/interaction/pan.js
  src/interaction/pinch.js
  src/interaction/swipe.js
Labels: PR: unreviewed, bug

#898 fix: 交互销毁时，注销事件
  src/interaction/new/base.js
  src/interaction/new/context.js
Labels: PR: unreviewed, bug

#899 chore: release 3.6.4-beta.6
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#900 chore: release 3.7.0-alpha.2
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#902 fix: 修复touchstart触发press时，没有设置direction
  src/graphic/event/controller.js
Labels: PR: reviewed-changes-requested, bug

#903 chore: release 3.6.4-beta.7
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore
