Repository antvis/F2, pull requests merged in 2020-04, with the labels that each got.

#828 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: unreviewed, chore

#829 chore: add leaks action
  .github/workflows/gitleaks.yml
Labels: PR: unreviewed, chore

#833 Fix interaction event hooks
  .github/workflows/ci.yml
  src/interaction/new/base.js
  test/unit/interaction/new/index-spec.js
  test/unit/test-util.js
Labels: PR: unreviewed

#835 chore: release 3.6.4-beta.1
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#840 feat: geom添加getRecords方法
  src/geom/base.js
  src/interaction/new/context.js
  test/unit/geom/geom-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#841 chore: release 3.6.4-beta.2
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore
