Repository antvis/F2, pull requests merged in 2020-07, with the labels that each got.

#937 fix: site 官网的一些错误
  examples/component/guide/index.zh.md
  examples/other/other/demo/meta.json
  examples/other/other/index.zh.md
  examples/relation/relation/demo/meta.json
  examples/relation/relation/index.en.md
  examples/relation/relation/index.zh.md
  gatsby-config.js
  package.json
  src/index-all.js
Labels: PR: unreviewed, bug

#940 fix: site build error
  examples/relation/relation/demo/meta.json
  examples/relation/relation/index.zh.md
  package.json
Labels: PR: unreviewed, bug

#920 feat: adjust interval
  src/chart/chart.js
  src/geom/base.js
  test/unit/geom/geom-init-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#918 chore: release 3.6.4
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: unreviewed, chore

#942 feat: add image shape
  src/graphic/index.js
  src/graphic/shape/image.js
  test/unit/graphic/shape/image-spec.js
Labels: PR: unreviewed, enhancement

#928 fix(event): fix EventEmit' s off missing the same function listener
  src/chart/plot.js
  src/geom/mixin/size.js
  src/graphic/event/emit.js
  src/plugin/gesture.js
  test/unit/graphic/event/emit-spec.js
Labels: PR: unreviewed, bug

#943 feat: 新增图片型图形文档和demo
  docs/api/graphic/shape.en.md
  docs/api/graphic/shape.zh.md
  examples/component/image/demo/image.js
  examples/component/image/demo/meta.json
  examples/component/image/index.en.md
  examples/component/image/index.zh.md
  test/unit/graphic/shape/image-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#944 chore: release 3.7.0-alpha.5
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#948 chore: release 3.7.0-alpha.6
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#950 fix: 补充types的定义
  test/unit/graphic/canvas-spec.js
  types/Plot.d.ts
  types/Util.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#951 fix(types): fix the types of the entries and plugins
  package.json
  scripts/patch-types.js
  types/index.d.ts
Labels: PR: unreviewed, bug

#952 chore: release 3.7.0-alpha.7
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#953 chore: release 3.7.0
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#956 docs: 修复文档上一些失效的链接
  docs/api/chart/gesture.en.md
  docs/api/chart/gesture.zh.md
  docs/tutorial/manual/miniprogram.en.md
  docs/tutorial/manual/miniprogram.zh.md
  docs/tutorial/manual/node-env.en.md
  docs/tutorial/manual/node-env.zh.md
Labels: PR: reviewed-changes-requested, documentation

#958 docs: uniform AntV navbar's order and naming
  gatsby-config.js
Labels: PR: reviewed-changes-requested, documentation

#961 docs: modify f2 cdn url
  docs/tutorial/getting-started.en.md
  docs/tutorial/getting-started.zh.md
Labels: PR: unreviewed, documentation

#965 deps: 升级@antv/scale
  package.json
  src/chart/controller/scale.js
  src/geom/base.js
  src/index-all.js
  src/index.js
  src/interaction/helper.js
  src/interaction/mixin/update-scale.js
  src/interaction/new/context.js
  src/plugin/filter.js
  src/scale/index.js
  src/scale/time-cat.js
  src/util/common.js
  test/bug/guide-html-spec.js
  test/bug/issue-151-spec.js
  test/bug/issue-216-spec.js
  test/bug/issue-550-spec.js
  test/unit/animation/detail-spec.js
  test/unit/chart/chart-spec.js
  test/unit/interaction/pan-spec.js
  test/unit/interaction/pinch-spec.js
  test/unit/plugin/guide-spec.js
Labels: PR: unreviewed, deps

#964 fix: 修复pieLabel插件判断矩形重叠的函数
  src/plugin/pie-label.js
  test/unit/plugin/pie-label-spec.js
Labels: PR: unreviewed, bug

#969 chore: release 3.7.1-beta.1
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#971 fix: Time cat ticks count
  package.json
  src/chart/controller/scale.js
  src/chart/controller/timecat-tick.js
  test/unit/chart/controller/timecat-tick-spec.js
Labels: PR: unreviewed, bug

#973 fix: transform arrow functions
  .babelrc
  package.json
  test/bug/issue-804-spec.js
Labels: PR: unreviewed, bug

#974 chore: release 3.7.1-beta.2
  package.json
  src/global.js
Labels: chore

#977 Fix demo data path
  examples/area/stacked/demo/area-none.js
  examples/candlestick/basic/demo/basic.js
  examples/candlestick/basic/demo/daily.js
  examples/candlestick/basic/demo/hour.js
  examples/column/basic/demo/pan.js
  examples/component/axis/demo/grid.js
  examples/component/axis/demo/label-callback.js
  examples/component/guide/demo/line.js
  examples/component/guide/demo/point.js
  examples/component/legend/demo/align.js
  examples/gallery/fitness-ring/demo/apple-watch.js
  examples/gallery/forecast/demo/basic.js
  examples/gallery/gauge/demo/basic.js
  examples/gallery/steps-record/demo/basic.js
  examples/heatmap/heatmap/demo/polar.js
  examples/line/basic/demo/pan.js
  examples/line/multiple/demo/series.js
  examples/line/other/demo/null.js
  examples/other/other/demo/word-cloud.js
  examples/point/scatter/demo/scatter.js
  src/animation/animate.js
Labels: PR: reviewed-changes-requested
