Repository antvis/F2, pull requests merged in 2020-08, with the labels that each got.

#980 feat: 添加repaint事件
  src/chart/chart.js
  src/chart/const.js
  test/unit/interaction/new/index-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#982 3.7
  examples/area/stacked/demo/area-none.js
  examples/candlestick/basic/demo/basic.js
  examples/candlestick/basic/demo/daily.js
  examples/candlestick/basic/demo/hour.js
  examples/column/basic/demo/pan.js
  examples/component/axis/demo/grid.js
  examples/component/axis/demo/label-callback.js
  examples/component/guide/demo/line.js
  examples/component/guide/demo/point.js
  examples/component/legend/demo/align.js
  examples/gallery/fitness-ring/demo/apple-watch.js
  examples/gallery/forecast/demo/basic.js
  examples/gallery/gauge/demo/basic.js
  examples/gallery/steps-record/demo/basic.js
  examples/heatmap/heatmap/demo/polar.js
  examples/line/basic/demo/pan.js
  examples/line/multiple/demo/series.js
  examples/line/other/demo/null.js
  examples/other/other/demo/word-cloud.js
  examples/point/scatter/demo/scatter.js
  package.json
  src/animation/animate.js
  src/chart/chart.js
  src/chart/const.js
  src/global.js
  test/unit/interaction/new/index-spec.js
Labels: PR: reviewed-changes-requested

#984 fix: 修复漏斗图legend点击后，label位置不调整 Fixed #979
  examples/funnel/basic/demo/basic.js
  examples/funnel/basic/demo/stroke.js
  examples/funnel/pyramid/demo/basic.js
  examples/funnel/pyramid/demo/scale.js
  examples/funnel/pyramid/demo/stroke.js
  src/geom/adjust/index.js
  src/plugin/interval-label.js
  test/unit/plugin/interval-label-spec.js
  test/unit/test-util.js
Labels: PR: reviewed-changes-requested, bug

#983 fix: 修复 interval 平移后不显示的问题 Fixed #954
  src/interaction/pan.js
  test/bug/issue-954-spec.js
Labels: PR: unreviewed, bug

#987 chore: 调整代码结构
  src/scale/linear-tick.js
  test/unit/scale/linear-tick-spec.js
Labels: PR: unreviewed, chore

#978 feat: 连续数值刻度算法
  src/chart/controller/scale.js
  src/scale/index.js
  src/scale/linear-tick.js
  src/scale/timecat-tick.js
  test/bug/guide-html-spec.js
  test/bug/issue-179-spec.js
  test/bug/issue-954-spec.js
  test/unit/animation/detail-spec.js
  test/unit/interaction/pan-spec.js
  test/unit/interaction/pinch-spec.js
  test/unit/plugin/interval-label-spec.js
  test/unit/plugin/tooltip-spec.js
  test/unit/scale/linear-tick-spec.js
  test/unit/scale/timecat-spec.js
Labels: PR: unreviewed, enhancement

#990 fix: 修复数据字段存在x,y时，再次mapping后，数据不对
  src/geom/base.js
  test/bug/issue-954-spec.js
  test/unit/geom/geom-spec.js
  test/unit/interaction/new/index-spec.js
Labels: PR: reviewed-changes-requested, bug

#991 fix: 特殊情况下interval不满足要求时，需要递归计算
  src/scale/linear-tick.js
  test/unit/scale/linear-tick-spec.js
Labels: PR: unreviewed, bug

#992 fix: 统一cat ticks 计算
  src/interaction/new/context.js
  src/scale/cat-tick.js
  src/scale/index.js
  test/unit/interaction/new/index-spec.js
  test/unit/scale/cat-spec.js
Labels: PR: unreviewed, bug

#993 chore: release 3.7.3
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: unreviewed, chore

#1001 Time cat export
  docs/tutorial/manual/node-env.en.md
  docs/tutorial/manual/node-env.zh.md
  docs/tutorial/manual/require.en.md
  docs/tutorial/manual/require.zh.md
  src/scale/time-cat.js
Labels: PR: unreviewed

#1003 chore: release 3.7.4
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: unreviewed, chore

#1005 fix: 修复当interval为小数时，小数位数会少1位
  src/scale/linear-tick.js
  test/bug/issue-145-spec.js
  test/unit/plugin/interval-label-spec.js
  test/unit/scale/linear-tick-spec.js
Labels: PR: unreviewed, bug

#1006 chore: release 3.7.5
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: unreviewed, chore

#1008 fix: linear NaN error
  src/scale/linear-tick.js
  test/unit/scale/linear-tick-spec.js
Labels: PR: unreviewed, bug

#1009 chore: release 3.7.6
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: unreviewed, chore
