Repository antvis/F2, pull requests merged in 2020-01, with the labels that each got.

#752 修改错别字
  examples/other/other/index.zh.md
Labels: PR: unreviewed

#754 fix: 修复非浏览器环境时，currentStyle报错
  package.json
  src/global.js
  src/graphic/canvas-element.js
Labels: PR: reviewed-changes-requested, bug

#755 chore: npm包添加src源文件
  .npmignore
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#756 fix: 未设置geometry时，clear报错
  src/plugin/tooltip.js
Labels: PR: reviewed-changes-requested, bug

#757 chore: 发布3.5.0-beta.6
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#762 fix: 修复tooltip touchend不消失的问题
  src/plugin/tooltip.js
Labels: PR: reviewed-changes-requested, bug

#740 feat: 多端多环境的适配与支持
  .npmignore
  demos/interval-symmetric.html
  examples/funnel/basic/demo/basic.js
  examples/funnel/basic/demo/meta.json
  examples/funnel/basic/demo/stroke.js
  examples/funnel/basic/index.en.md
  examples/funnel/basic/index.zh.md
  examples/funnel/pyramid/demo/basic.js
  examples/funnel/pyramid/demo/meta.json
  examples/funnel/pyramid/demo/scale.js
  examples/funnel/pyramid/demo/stroke.js
  examples/funnel/pyramid/index.en.md
  examples/funnel/pyramid/index.zh.md
  gatsby-config.js
  package.json
  src/chart/chart.js
  src/coord/base.js
  src/coord/cartesian.js
  src/coord/polar.js
  src/geom/adjust/index.js
  src/geom/adjust/symmetric.js
  src/geom/base.js
  src/geom/shape/interval.js
  src/global.js
  src/graphic/canvas-element.js
  src/graphic/canvas.js
  src/index-all.js
  src/plugin/interval-label.js
  src/plugin/tooltip.js
  src/util/dom.js
  test/unit/coord/base-spec.js
  test/unit/core-spec.js
  test/unit/geom/geom-spec.js
  test/unit/plugin/interval-label-spec.js
Labels: PR: unreviewed, enhancement

#763 chore: release 3.5.0
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#767 feat: 升级@antv/util
  .eslintrc
  package.json
  src/util/array.js
  src/util/common.js
  src/util/dom.js
  src/util/helper.js
  test/bug/issue-467-spec.js
  test/bug/issue-468-spec.js
  test/bug/issue-488-spec.js
  test/bug/issue-514-spec.js
  test/bug/issue-543-spec.js
  test/bug/issue-550-spec.js
  test/bug/issue-586-spec.js
  test/bug/legend-filter-spec.js
  test/unit/attr/base-spec.js
  test/unit/chart/controller/scale-spec.js
  test/unit/component/axis/line-axis-spec.js
  test/unit/component/guide/arc-spec.js
  test/unit/coord/circle-spec.js
  test/unit/graphic/shape/text-spec.js
  test/unit/plugin/gesture-spec.js
Labels: PR: unreviewed, enhancement
