Repository antvis/F2, pull requests merged in 2020-11, with the labels that each got.

#1071 fix 主题设置问题和hammerjs引用导致小程序端报错问题
  src/global.js
  src/interaction/base.js
Labels: PR: unreviewed

#1072 chore: release 3.7.8
  package.json
  src/global.js
Labels: PR: unreviewed

#1028 feat: export tooltip component
  src/index.js
Labels: PR: unreviewed, enhancement

#1012 feat: 添加shape的无障碍处理
  src/aria-lang.CN.js
  src/chart/chart.js
  src/chart/controller/axis.js
  src/geom/aria/util.js
  src/geom/base.js
  src/global.js
  src/graphic/canvas-element.js
  src/graphic/canvas.js
  src/graphic/container.js
  src/graphic/element.js
  src/graphic/shape/text.js
  src/plugin/legend.js
  src/util/common.js
  test/fixtures/accessibility-spec.js
  test/unit/graphic/canvas-spec.js
  test/unit/plugin/legend-spec.js
Labels: PR: unreviewed, enhancement

#1076 docs: 添加无障碍aria的配置和使用文档
  docs/api/chart/chart.zh.md
  examples/basic/demo/meta.json
  examples/column/basic/demo/aria.js
  examples/column/basic/demo/meta.json
  examples/line/basic/demo/aria.js
  examples/line/basic/demo/meta.json
Labels: PR: reviewed-changes-requested

#1081 feat: 支持外部注册和扩展渲染引擎
  package.json
  src/animation/detail.js
  src/animation/group.js
  src/chart/chart.js
  src/chart/controller/axis.js
  src/component/guide/region-filter.js
  src/component/list.js
  src/component/tooltip.js
  src/graphic/engine/canvas-element.js
  src/graphic/engine/canvas.js
  src/graphic/engine/container.js
  src/graphic/engine/element.js
  src/graphic/engine/group.js
  src/graphic/engine/index.js
  src/graphic/engine/shape/arc.js
  src/graphic/engine/shape/circle.js
  src/graphic/engine/shape/custom.js
  src/graphic/engine/shape/image.js
  src/graphic/engine/shape/index.js
  src/graphic/engine/shape/line.js
  src/graphic/engine/shape/marker.js
  src/graphic/engine/shape/polygon.js
  src/graphic/engine/shape/polyline.js
  src/graphic/engine/shape/rect.js
  src/graphic/engine/shape/sector.js
  src/graphic/engine/shape/shape.js
  src/graphic/engine/shape/text.js
  src/graphic/index.js
  src/index.js
  test/bug/issue-468-spec.js
  test/fixtures/canvas-spec.js
  test/fixtures/svg-spec.js
  test/unit/component/axis/circle-axis-spec.js
  test/unit/component/axis/line-axis-spec.js
  test/unit/component/guide/arc-spec.js
  test/unit/component/guide/html-spec.js
  test/unit/component/guide/line-spec.js
  test/unit/component/guide/point-spec.js
  test/unit/component/guide/rect-spec.js
  test/unit/component/guide/tag-spec.js
  test/unit/component/guide/text-spec.js
  test/unit/geom/geom-enhance-spec.js
  test/unit/geom/geom-spec.js
  test/unit/geom/shape/shape-spec.js
  test/unit/graphic/animate-spec.js
  test/unit/graphic/canvas-spec.js
  test/unit/graphic/element-spec.js
  test/unit/graphic/event/controller-spec.js
  test/unit/graphic/group-spec.js
  test/unit/graphic/shape-spec.js
  test/unit/graphic/shape/arc-spec.js
  test/unit/graphic/shape/circle-spec.js
  test/unit/graphic/shape/custom-spec.js
  test/unit/graphic/shape/image-spec.js
  test/unit/graphic/shape/line-spec.js
  test/unit/graphic/shape/polygon-spec.js
  test/unit/graphic/shape/polyline-spec.js
  test/unit/graphic/shape/rect-spec.js
  test/unit/graphic/shape/sector-spec.js
  test/unit/graphic/shape/text-spec.js
Labels: PR: unreviewed

#1082 chore: release 3.8.0-alpha.1
  package.json
  src/global.js
Labels: PR: unreviewed

#1077 feat: 添加地图demo
  examples/other/map/demo/map.js
  examples/other/map/demo/meta.json
  examples/other/map/index.en.md
  examples/other/map/index.zh.md
Labels: PR: unreviewed

#1083 chore: chart types 添加renderer参数
  types/Chart.d.ts
Labels: PR: unreviewed

#1088 feat: 新增横屏的支持
  examples/creative/apple/index.zh.md
  examples/creative/case/demo/apple-watch.js
  examples/creative/case/demo/forecast.js
  examples/creative/case/demo/gauge.js
  examples/creative/case/demo/landscape.js
  examples/creative/case/demo/meta.json
  examples/creative/case/demo/steps-record.js
  examples/creative/case/index.en.md
  examples/creative/case/index.zh.md
  src/chart/chart.js
  src/graphic/event/controller.js
  src/util/dom.js
  test/fixtures/canvas-spec.js
  test/fixtures/landscape-spec.js
  types/Chart.d.ts
Labels: PR: unreviewed

#1084 docs: 添加tooltip show hide 的文档说明
  docs/api/chart/tooltip.zh.md
Labels: PR: unreviewed

#1089 docs: 修改demo
  examples/creative/case/demo/landscape.js
  gatsby-config.js
Labels: PR: unreviewed

#1090 chore: release 3.8.0-alpha.2
  package.json
  src/global.js
Labels: PR: unreviewed

#1091 fix: remove circular dependency
  .github/workflows/mirror.yml
  src/util/dom.js
Labels: PR: unreviewed

#1092 docs: 修改官网首页example链接
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#1094 fix: 修复部分404文档跳转链接
  docs/api/animate.en.md
  docs/api/animate.zh.md
  docs/api/graphic/shape.en.md
  docs/api/graphic/shape.zh.md
  docs/tutorial/miniprogram.en.md
  docs/tutorial/miniprogram.zh.md
Labels: PR: reviewed-changes-requested

#1093 chore: release 3.8.0
  package.json
  src/global.js
Labels: PR: unreviewed

#1095 docs: 修改changelog
  CHANGELOG.md
Labels: PR: unreviewed
